### ISSUE TITLE
Questions on the paper titled "Pruning and Quantizing Neural Belief Propagation Decoders"

### ISSUE THREAD

**Issue by YutaiSun** [bbgra/pruning_nbp#2]
Dear Dr. Buchberger,

I'm an undergraduate in Southeast University, China. My bachelor thesis is about AI-based sparse channel decoding. I'm reading your papers "Pruning and Quantizing Neural Belief Propagation Decoders" and "Pruning neural belief propagation decoders". When I tried to reproduce the simulation on RM(2,5), I got some problems about gradient calculation. Perhaps I still miss some details after my reading this paper in many times. 
I found that you mentioned the source code is available in [21]. However, the repository is empty. If possible, could you kindly share the source code? I will be very grateful and have a much better understanding of your work.

Many thanks!
Yutai
11-02-2022

**Comment by mlscsdn** [comment]
东南的好兄弟，请问你要到源代码了吗

**Comment by YutaiSun** [comment]
@mlscsdn Not yet.
